{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "CommandNotFoundError: Your shell has not been properly configured to use 'conda deactivate'.\n",
      "To initialize your shell, run\n",
      "\n",
      "    $ conda init <SHELL_NAME>\n",
      "\n",
      "Currently supported shells are:\n",
      "  - bash\n",
      "  - fish\n",
      "  - tcsh\n",
      "  - xonsh\n",
      "  - zsh\n",
      "  - powershell\n",
      "\n",
      "See 'conda init --help' for more information and options.\n",
      "\n",
      "IMPORTANT: You may need to close and restart your shell after running 'conda init'.\n",
      "\n",
      "\n",
      "\n",
      "CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.\n",
      "To initialize your shell, run\n",
      "\n",
      "    $ conda init <SHELL_NAME>\n",
      "\n",
      "Currently supported shells are:\n",
      "  - bash\n",
      "  - fish\n",
      "  - tcsh\n",
      "  - xonsh\n",
      "  - zsh\n",
      "  - powershell\n",
      "\n",
      "See 'conda init --help' for more information and options.\n",
      "\n",
      "IMPORTANT: You may need to close and restart your shell after running 'conda init'.\n",
      "\n",
      "\n"
     ]
    }
   ],
   "source": [
    "!source activate\n",
    "!conda deactivate\n",
    "!conda activate naturalistic"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting brainconn\n",
      "  Cloning https://github.com/FIU-Neuro/brainconn to /private/var/folders/h9/b4fl72pj2254z2q1503mxdd00000gn/T/pip-install-b0aoi561/brainconn_06592fadc5f044c788d5e98949aaf279\n",
      "  Running command git clone --quiet https://github.com/FIU-Neuro/brainconn /private/var/folders/h9/b4fl72pj2254z2q1503mxdd00000gn/T/pip-install-b0aoi561/brainconn_06592fadc5f044c788d5e98949aaf279\n",
      "  Resolved https://github.com/FIU-Neuro/brainconn to commit 8cd436a885c9f823ef7789aa032cc2119318ff59\n",
      "  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25hRequirement already satisfied: numpy in /Users/chunyilee/miniconda3/lib/python3.10/site-packages (from brainconn) (1.23.5)\n",
      "Requirement already satisfied: scipy in /Users/chunyilee/miniconda3/lib/python3.10/site-packages (from brainconn) (1.10.0)\n",
      "Building wheels for collected packages: brainconn\n",
      "  Building wheel for brainconn (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25h  Created wheel for brainconn: filename=brainconn-0.0.1-py3-none-any.whl size=108871 sha256=d59b0a8585b44bd46515c8d65c3b8effd06fdf9d2fafb06a7dedd670889b9167\n",
      "  Stored in directory: /private/var/folders/h9/b4fl72pj2254z2q1503mxdd00000gn/T/pip-ephem-wheel-cache-uibn6vge/wheels/3b/cb/60/093f3f43132a041b25dc0e2cc8641882231156608cc7d67ca5\n",
      "Successfully built brainconn\n",
      "Installing collected packages: brainconn\n",
      "Successfully installed brainconn-0.0.1\n"
     ]
    }
   ],
   "source": [
    "!pip install git+https://github.com/FIU-Neuro/brainconn#egg=brainconn"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting package metadata (current_repodata.json): failed\n",
      "\n",
      "# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<\n",
      "\n",
      "    Traceback (most recent call last):\n",
      "      File \"/Users/chunyilee/miniconda3/lib/python3.10/site-packages/conda/gateways/repodata/__init__.py\", line 161, in conda_http_errors\n",
      "        yield\n",
      "      File \"/Users/chunyilee/miniconda3/lib/python3.10/site-packages/conda/gateways/repodata/__init__.py\", line 127, in repodata\n",
      "        response.raise_for_status()\n",
      "      File \"/Users/chunyilee/miniconda3/lib/python3.10/site-packages/requests/models.py\", line 1021, in raise_for_status\n",
      "        raise HTTPError(http_error_msg, response=self)\n",
      "    requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://conda.anaconda.org/brainiak/noarch/current_repodata.json\n",
      "    \n",
      "    During handling of the above exception, another exception occurred:\n",
      "    \n",
      "    Traceback (most recent call last):\n",
      "      File \"/Users/chunyilee/miniconda3/lib/python3.10/site-packages/conda/core/subdir_data.py\", line 366, in _load\n",
      "        raw_repodata_str = self._repo.repodata(cache.state)  # type: ignore\n",
      "      File \"/Users/chunyilee/miniconda3/lib/python3.10/site-packages/conda/gateways/repodata/__init__.py\", line 120, in repodata\n",
      "        with conda_http_errors(self._url, filename):\n",
      "      File \"/Users/chunyilee/miniconda3/lib/python3.10/contextlib.py\", line 153, in __exit__\n",
      "        self.gen.throw(typ, value, traceback)\n",
      "      File \"/Users/chunyilee/miniconda3/lib/python3.10/site-packages/conda/gateways/repodata/__init__.py\", line 226, in conda_http_errors\n",
      "        raise UnavailableInvalidChannel(\n",
      "    conda.exceptions.UnavailableInvalidChannel: HTTP 404 NOT FOUND for channel brainiak <https://conda.anaconda.org/brainiak>\n",
      "    \n",
      "    The channel is not accessible or is invalid.\n",
      "    \n",
      "    You will need to adjust your conda configuration to proceed.\n",
      "    Use `conda config --show channels` to view your configuration's current state,\n",
      "    and use `conda config --show-sources` to view config file locations.\n",
      "    \n",
      "    \n",
      "    During handling of the above exception, another exception occurred:\n",
      "    \n",
      "    Traceback (most recent call last):\n",
      "      File \"/Users/chunyilee/miniconda3/lib/python3.10/site-packages/conda/exceptions.py\", line 1132, in __call__\n",
      "        return func(*args, **kwargs)\n",
      "      File \"/Users/chunyilee/miniconda3/lib/python3.10/site-packages/conda/cli/main.py\", line 69, in main_subshell\n",
      "        exit_code = do_call(args, p)\n",
      "      File \"/Users/chunyilee/miniconda3/lib/python3.10/site-packages/conda/cli/conda_argparse.py\", line 122, in do_call\n",
      "        return getattr(module, func_name)(args, parser)\n",
      "      File \"/Users/chunyilee/miniconda3/lib/python3.10/site-packages/conda/notices/core.py\", line 121, in wrapper\n",
      "        return func(*args, **kwargs)\n",
      "      File \"/Users/chunyilee/miniconda3/lib/python3.10/site-packages/conda/cli/main_install.py\", line 20, in execute\n",
      "        install(args, parser, 'install')\n",
      "      File \"/Users/chunyilee/miniconda3/lib/python3.10/site-packages/conda/cli/install.py\", line 264, in install\n",
      "        unlink_link_transaction = solver.solve_for_transaction(\n",
      "      File \"/Users/chunyilee/miniconda3/lib/python3.10/site-packages/conda/core/solve.py\", line 134, in solve_for_transaction\n",
      "        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,\n",
      "      File \"/Users/chunyilee/miniconda3/lib/python3.10/site-packages/conda/core/solve.py\", line 177, in solve_for_diff\n",
      "        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,\n",
      "      File \"/Users/chunyilee/miniconda3/lib/python3.10/site-packages/conda/core/solve.py\", line 282, in solve_final_state\n",
      "        ssc = self._collect_all_metadata(ssc)\n",
      "      File \"/Users/chunyilee/miniconda3/lib/python3.10/site-packages/conda/common/io.py\", line 84, in decorated\n",
      "        return f(*args, **kwds)\n",
      "      File \"/Users/chunyilee/miniconda3/lib/python3.10/site-packages/conda/core/solve.py\", line 449, in _collect_all_metadata\n",
      "        index, r = self._prepare(prepared_specs)\n",
      "      File \"/Users/chunyilee/miniconda3/lib/python3.10/site-packages/conda/core/solve.py\", line 1064, in _prepare\n",
      "        reduced_index = get_reduced_index(self.prefix, self.channels,\n",
      "      File \"/Users/chunyilee/miniconda3/lib/python3.10/site-packages/conda/core/index.py\", line 267, in get_reduced_index\n",
      "        new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,\n",
      "      File \"/Users/chunyilee/miniconda3/lib/python3.10/site-packages/conda/core/subdir_data.py\", line 169, in query_all\n",
      "        result = tuple(chain.from_iterable(executor.map(subdir_query, channel_urls)))\n",
      "      File \"/Users/chunyilee/miniconda3/lib/python3.10/concurrent/futures/_base.py\", line 621, in result_iterator\n",
      "        yield _result_or_cancel(fs.pop())\n",
      "      File \"/Users/chunyilee/miniconda3/lib/python3.10/concurrent/futures/_base.py\", line 319, in _result_or_cancel\n",
      "        return fut.result(timeout)\n",
      "      File \"/Users/chunyilee/miniconda3/lib/python3.10/concurrent/futures/_base.py\", line 451, in result\n",
      "        return self.__get_result()\n",
      "      File \"/Users/chunyilee/miniconda3/lib/python3.10/concurrent/futures/_base.py\", line 403, in __get_result\n",
      "        raise self._exception\n",
      "      File \"/Users/chunyilee/miniconda3/lib/python3.10/concurrent/futures/thread.py\", line 58, in run\n",
      "        result = self.fn(*self.args, **self.kwargs)\n",
      "      File \"/Users/chunyilee/miniconda3/lib/python3.10/site-packages/conda/core/subdir_data.py\", line 158, in subdir_query\n",
      "        return tuple(\n",
      "      File \"/Users/chunyilee/miniconda3/lib/python3.10/site-packages/conda/core/subdir_data.py\", line 174, in query\n",
      "        self.load()\n",
      "      File \"/Users/chunyilee/miniconda3/lib/python3.10/site-packages/conda/core/subdir_data.py\", line 264, in load\n",
      "        _internal_state = self._load()\n",
      "      File \"/Users/chunyilee/miniconda3/lib/python3.10/site-packages/conda/core/subdir_data.py\", line 379, in _load\n",
      "        return self._load()\n",
      "      File \"/Users/chunyilee/miniconda3/lib/python3.10/site-packages/conda/core/subdir_data.py\", line 315, in _load\n",
      "        cache.load_state()  # XXX should this succeed even if FileNotFound?\n",
      "      File \"/Users/chunyilee/miniconda3/lib/python3.10/site-packages/conda/gateways/repodata/__init__.py\", line 570, in load_state\n",
      "        self.load(state_only=True)\n",
      "      File \"/Users/chunyilee/miniconda3/lib/python3.10/site-packages/conda/gateways/repodata/__init__.py\", line 528, in load\n",
      "        state = json.loads(state_file.read())\n",
      "      File \"/Users/chunyilee/miniconda3/lib/python3.10/json/__init__.py\", line 346, in loads\n",
      "        return _default_decoder.decode(s)\n",
      "      File \"/Users/chunyilee/miniconda3/lib/python3.10/json/decoder.py\", line 340, in decode\n",
      "        raise JSONDecodeError(\"Extra data\", s, end)\n",
      "    json.decoder.JSONDecodeError: Extra data: line 7 column 2 (char 186)\n",
      "\n",
      "`$ /Users/chunyilee/miniconda3/bin/conda install -c brainiak -c defaults -c conda-forge brainiak`\n",
      "\n",
      "  environment variables:\n",
      "                 CIO_TEST=<not set>\n",
      "        CONDA_DEFAULT_ENV=base\n",
      "                CONDA_EXE=/Users/chunyilee/miniconda3/bin/conda\n",
      "             CONDA_PREFIX=/Users/chunyilee/miniconda3\n",
      "    CONDA_PROMPT_MODIFIER=(base)\n",
      "         CONDA_PYTHON_EXE=/Users/chunyilee/miniconda3/bin/python\n",
      "               CONDA_ROOT=/Users/chunyilee/miniconda3\n",
      "              CONDA_SHLVL=1\n",
      "           CURL_CA_BUNDLE=<not set>\n",
      "               LD_PRELOAD=<not set>\n",
      "                     PATH=/opt/local/bin:/opt/local/sbin:/Users/chunyilee/miniconda3/bin:/Users/\n",
      "                          chunyilee/miniconda3/condabin:/Users/chunyilee/.nvm/versions/node/v10.\n",
      "                          16.3/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Users/\n",
      "                          chunyilee/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/\n",
      "                          opt/X11/bin\n",
      "       REQUESTS_CA_BUNDLE=<not set>\n",
      "            SSL_CERT_FILE=<not set>\n",
      "\n",
      "     active environment : base\n",
      "    active env location : /Users/chunyilee/miniconda3\n",
      "            shell level : 1\n",
      "       user config file : /Users/chunyilee/.condarc\n",
      " populated config files : /Users/chunyilee/.condarc\n",
      "          conda version : 23.3.1\n",
      "    conda-build version : not installed\n",
      "         python version : 3.10.9.final.0\n",
      "       virtual packages : __archspec=1=x86_64\n",
      "                          __osx=10.16=0\n",
      "                          __unix=0=0\n",
      "       base environment : /Users/chunyilee/miniconda3  (writable)\n",
      "      conda av data dir : /Users/chunyilee/miniconda3/etc/conda\n",
      "  conda av metadata url : None\n",
      "           channel URLs : https://conda.anaconda.org/brainiak/osx-64\n",
      "                          https://conda.anaconda.org/brainiak/noarch\n",
      "                          https://repo.anaconda.com/pkgs/main/osx-64\n",
      "                          https://repo.anaconda.com/pkgs/main/noarch\n",
      "                          https://repo.anaconda.com/pkgs/r/osx-64\n",
      "                          https://repo.anaconda.com/pkgs/r/noarch\n",
      "                          https://conda.anaconda.org/conda-forge/osx-64\n",
      "                          https://conda.anaconda.org/conda-forge/noarch\n",
      "          package cache : /Users/chunyilee/miniconda3/pkgs\n",
      "                          /Users/chunyilee/.conda/pkgs\n",
      "       envs directories : /Users/chunyilee/miniconda3/envs\n",
      "                          /Users/chunyilee/.conda/envs\n",
      "               platform : osx-64\n",
      "             user-agent : conda/23.3.1 requests/2.28.1 CPython/3.10.9 Darwin/21.6.0 OSX/10.16\n",
      "                UID:GID : 501:20\n",
      "             netrc file : None\n",
      "           offline mode : False\n",
      "\n",
      "\n",
      "An unexpected error has occurred. Conda has prepared the above report.\n",
      "\n",
      "If submitted, this report will be used by core maintainers to improve\n",
      "future releases of conda.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Would you like conda to send this report to the core maintainers? [y/N]: \r\n",
      "Timeout reached. No report sent.\r\n",
      "\r\n"
     ]
    }
   ],
   "source": [
    "!conda install -c brainiak -c defaults -c conda-forge brainiak"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "!pip install nibabel datalad nilearn nltools hypertools timecorr pliers statesegmentation networkx nltk requests urllib3"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "naturalistic",
   "language": "python",
   "name": "naturalistic"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
